### ISSUE TITLE
Create LAGs in F5OS

### ISSUE THREAD

**Issue by Hoonigan-013** [F5Networks/terraform-provider-f5os#25]
Hello,

Checking the documentation doesn't have a resource to create a LAG in F5OS, for now is it unavailable?

Thanks.

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1306.

**Comment by RavinderReddyF5** [comment]
Hi @Hoonigan-013 Lag resource support added in v1.3.0. please open new issue if any problem seen
