### ISSUE TITLE
When applying changes to f5os_interface.test_interface, provider "provider[\"registry.terraform.io/f5networks/f5os\"]" produced an unexpected new value

### ISSUE THREAD

**Issue by francisfcm** [F5Networks/terraform-provider-f5os#30]
### Terraform Version
Terraform v1.6.2
on linux_arm
+ provider registry.terraform.io/f5networks/f5os v1.3.0

### Affected Resource(s)
resource "f5os_vlan" "vlan1" {
  vlan_id = var.vlans[0]
  name    = "vlan${var.vlans[0]}"
}

resource "f5os_vlan" "vlan2" {
  vlan_id = var.vlans[1]
  name    = "vlan${var.vlans[1]}"
}

resource "f5os_vlan" "vlan3" {
  vlan_id = var.vlans[2]
  name    = "vlan${var.vlans[2]}"
}

resource "f5os_interface" "test_interface" {
  enabled     = true
  name        = var.interface
  trunk_vlans = var.vlans
}

### Terraform Configuration Files
variables.tf:
variable "interface" {
  description = "F5OS-A interface"
  default     = ""
}
variable "vlans" {
  description = "list of vlans"
  default     = []
}

inputs.auto.tfvars:
vlans                = [188, 1328, 1249]
interface            = "3.0"

### Debug Output
https://gist.github.com/francisfcm/7768c0dfd7416303d31d3c30fcfb776b

### Panic Output
None

### Expected Behavior
No errors when VLANs are created and tagged to interface.

### Actual Behavior
Error when performing terraform apply
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to f5os_interface.test_interface, provider "provider[\"registry.terraform.io/f5networks/f5os\"]" produced an unexpected new value: .trunk_vlans[1]: was
│ cty.NumberIntVal(1328), but now cty.NumberIntVal(1249).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to f5os_interface.test_interface, provider "provider[\"registry.terraform.io/f5networks/f5os\"]" produced an unexpected new value: .trunk_vlans[2]: was
│ cty.NumberIntVal(1249), but now cty.NumberIntVal(1328).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷

### Steps to Reproduce
Add "f5os_vlan" and "f5os_interface" resources to the main.tf and then terraform apply to see the errors.

### Important Factoids
The VLANs were created and tagged to the correct interface and the tenant was also deployed successfully but produces errors about the VLANs at the end of the terraform apply output which causes confusion with regards whether did the operation go through successfully or not. This also disrupts the automation process when such errors appear.

### References
The VLANs and interface configurations are created based on the following docs:
https://github.com/F5Networks/terraform-provider-f5os/blob/main/docs/resources/vlan.md
https://github.com/F5Networks/terraform-provider-f5os/blob/main/docs/resources/interface.md

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1374.
