### ISSUE TITLE
F5os CLIENT ERROR // f5os_config_backup // invalid value for local-file

### ISSUE THREAD

**Issue by dgst77** [F5Networks/terraform-provider-f5os#68]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

 1.9.7 

### Affected Resource(s)
Please list the resources as a list, for example:
f5os__config_backup

### Terraform Configuration Files

please note remote host has been added as know host on tenant running TMOS on Rseries

resource "f5os_config_backup" "test" {
  name            = "test_cfg_backup"
  remote_host     = "1.2.3.4"
  remote_user     = "corpuser"
  remote_password = "password"
  remote_path     = "/upload/test_cfg_backup"
  protocol        = "scp"
}

### Debug Output
 f5os client error 

failure while creating config backup, got error : invalid for : local-file in /f5-utils-file-transfer:file/f5-utils-file-transfer:export/f5-utils-file-transfer:local-file:
"configs/backupfilename-2024-10-08T20:39:55Z is an invalid value

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

backup file should be created and exported to remote host

### Actual Behavior
backfile is created but never exported to remote host 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform init
2. terraform plan
3. terraform apply

**Comment by dgst77** [comment]
Platform is Rseries

**Comment by dgst77** [comment]
F5OS version is 1.7.0-871 and Rseries platform is 12800

**Comment by pgouband** [comment]
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1689.

**Comment by RavinderReddyF5** [comment]
Hi @dgst77,
I don't see any issue on latest TF F5OS provider:

```
➜  terraform-provider-f5os git:(main) terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # f5os_config_backup.test will be created
  + resource "f5os_config_backup" "test" {
      + id              = (known after apply)
      + name            = "test_cfg_backup_ravi"
      + protocol        = "scp"
      + remote_host     = "10.145.85.64"
      + remote_password = (sensitive value)
      + remote_path     = "/root/uploads"
      + remote_user     = "xxxx"
      + timeout         = 150
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

f5os_config_backup.test: Creating...
f5os_config_backup.test: Creation complete after 7s [id=test_cfg_backup_ravi]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
➜  terraform-provider-f5os git:(main)
➜  terraform-provider-f5os git:(main)

➜  terraform-provider-f5os git:(main) terraform apply
f5os_config_backup.test: Refreshing state... [id=test_cfg_backup_ravi]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by pgouband** [comment]
Hi @dgst77,

We are not able to reproduce it so we will close this issue. Please reopen it or open a new issue if you are facing it again.
