### ISSUE TITLE
 When applying changes to f5os_tenant.test2, provider "provider[\"registry.terraform.io/f5networks/f5os\"]" produced an unexpected new value: .nodes: was cty.ListVal([]cty.Value{cty.NumberIntVal(1)}), but now null.

### ISSUE THREAD

**Issue by jkwok018** [F5Networks/terraform-provider-f5os#75]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.9.8

### Terraform Configuration Files
terraform {
  required_providers {
    f5os = {
      source  = "F5Networks/f5os"
      version = "1.0.0"
    }
  }
}

provider "f5os" {
  host        = "10.154.88.11"
  username    = "admin"
  password    = "admin"
}

resource "f5os_vlan" "vlan-id" {
  vlan_id    = 126
  name       = "vlan"
}

resource "f5os_tenant" "test2" {
  name              = "testtenant"
  image_name        = "BIGIP-17.1.1.4-0.0.9.ALL-F5OS.qcow2.zip.bundle"
  mgmt_ip           = "10.154.88.86"
  mgmt_gateway      = "10.154.88.254"
  mgmt_prefix       = 24
  type              = "BIG-IP"
  cpu_cores         = 8
  nodes             = [1]
  vlans             = [126]
  timeout           = 360
  running_state     = "deployed"
  virtual_disk_size = 82
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
It should create the tenant without error

### Actual Behavior
What actually happened?
It create the tenant, but there is error message out

Error: Provider produced inconsistent result after apply
│
│ When applying changes to f5os_tenant.test2, provider "provider[\"registry.terraform.io/f5networks/f5os\"]" produced an unexpected new value: .nodes: was
│ cty.ListVal([]cty.Value{cty.NumberIntVal(1)}), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by RavinderReddyF5** [comment]
Hi @jkwok018 ,
can you please try it on latest version of F5OS provider.

```
terraform {
  required_providers {
    f5os = {
      source = "F5Networks/f5os"
      version = "1.4.0"
    }
  }
}

provider "f5os" {
  # Configuration options
}
```

**Comment by jkwok018** [comment]
hi @RavinderReddyF5 

Thank you very much.

After changing the version to "1.4.0" it works now.
